### ISSUE TITLE
Color is deprecated, please switch to Colors

### ISSUE THREAD

**Issue by timholy** [rennis250/Sparrow.jl#1]
See https://github.com/JuliaLang/METADATA.jl/pull/3769; we're about to make Color uninstallable on julia 0.4.

Transition info is [here](https://github.com/JuliaGraphics/Colors.jl#migrating-from-colorjl).

**Comment by rennis250** [comment]
Right. I'll get on that, thanks.

**Comment by rennis250** [comment]
Done, thanks.

**Comment by timholy** [comment]
Thanks!
